In [1]:
import numpy as np 


In [2]:
tags = ["Noun", "Verb","Adverb"]

print(tags)

['Noun', 'Verb', 'Adverb']


In [3]:
words = ["Dogs", "Bark","Ranjith","Eats","Breakfast","Slowly"]

word_to_index = {
    "Dogs": 0,
    "Bark": 1,
    "Ranjith": 2,
    "Eats": 3,
    "Breakfast": 4,
    "Slowly":5
}

print(word_to_index)

{'Dogs': 0, 'Bark': 1, 'Ranjith': 2, 'Eats': 3, 'Breakfast': 4, 'Slowly': 5}


In [4]:
init_prob = np.array([
    0.5,
    0.3,
    0.2
    
])

print(init_prob)

[0.5 0.3 0.2]


In [5]:
transition = np.array([
   [0.5, 0.4, 0.1],
    [0.3, 0.4, 0.3],
    [0.4, 0.3, 0.3]
])

print(transition)

[[0.5 0.4 0.1]
 [0.3 0.4 0.3]
 [0.4 0.3 0.3]]


In [6]:
emission = np.array([
    [0.8, 0.2, 0.9, 0.1, 0.8, 0.1],
    [0.1, 0.9, 0.1, 0.9, 0.2, 0.1],
    [0.1, 0.1, 0.0, 0.0, 0.0, 0.8]
])

print(emission)

[[0.8 0.2 0.9 0.1 0.8 0.1]
 [0.1 0.9 0.1 0.9 0.2 0.1]
 [0.1 0.1 0.  0.  0.  0.8]]


In [7]:
log_init = np.log(init_prob + 1e-10)

log_trans = np.log(transition + 1e-10)

log_emit = np.log(emission + 1e-10)

print(log_init)

[-0.69314718 -1.2039728  -1.60943791]


In [8]:
def viterbi(sentence):

    T = len(sentence)

    N = len(tags)

    dp = np.full((N, T), -np.inf)

    backpointer = np.zeros((N, T), dtype=int)

    dp[:, 0] = log_init + log_emit[:, sentence[0]]

    for t in range(1, T):

        for j in range(N):

            scores = (
                dp[:, t-1]
                + log_trans[:, j]
                + log_emit[j, sentence[t]]
            )

            backpointer[j, t] = np.argmax(scores)

            dp[j, t] = np.max(scores)

    best_path = [np.argmax(dp[:, -1])]

    for t in range(T-1, 0, -1):

        best_path.append(
            backpointer[best_path[-1], t]
        )

    best_path.reverse()

    return best_path

In [9]:
sentence = ["Ranjith", "Eats", "Breakfast","Slowly"]

sentence_index = [
    word_to_index[word]
    for word in sentence
]

print(sentence_index)

[2, 3, 4, 5]


In [10]:
best_tags = viterbi(sentence_index)

print(best_tags)

[np.int64(0), np.int64(1), np.int64(0), np.int64(2)]


In [11]:
print("Sentence:", sentence)

print("\nPredicted Tags:")

for word, tag in zip(sentence, best_tags):
    print(word, "->", tags[tag])

Sentence: ['Ranjith', 'Eats', 'Breakfast', 'Slowly']

Predicted Tags:
Ranjith -> Noun
Eats -> Verb
Breakfast -> Noun
Slowly -> Adverb
