In [5]:
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer


In [6]:
# ----------------------------
# Sample Documents
# ----------------------------
documents = [
    "I love machine learning",
    "Machine learning is fun",
    "I enjoy learning Python",
    "Python is powerful"
]


In [7]:
# ----------------------------
# Bag of Words
# ----------------------------

bow = CountVectorizer()
bow_matrix = bow.fit_transform(documents)

print("Bag of Words:")
print(bow.get_feature_names_out())

print("\nBag of Words Matrix:")
print(bow_matrix.toarray())


Bag of Words:
['enjoy' 'fun' 'is' 'learning' 'love' 'machine' 'powerful' 'python']

Bag of Words Matrix:
[[0 0 0 1 1 1 0 0]
 [0 1 1 1 0 1 0 0]
 [1 0 0 1 0 0 0 1]
 [0 0 1 0 0 0 1 1]]


In [8]:
# ----------------------------
# TF-IDF
# ----------------------------

tfidf = TfidfVectorizer()
tfidf_matrix = tfidf.fit_transform(documents)

print("\nBag of Words:")
print(tfidf.get_feature_names_out())

print("\nTF-IDF Matrix:")
print(np.round(tfidf_matrix.toarray(), 2))



Bag of Words:
['enjoy' 'fun' 'is' 'learning' 'love' 'machine' 'powerful' 'python']

TF-IDF Matrix:
[[0.   0.   0.   0.45 0.7  0.55 0.   0.  ]
 [0.   0.61 0.48 0.39 0.   0.48 0.   0.  ]
 [0.7  0.   0.   0.45 0.   0.   0.   0.55]
 [0.   0.   0.53 0.   0.   0.   0.67 0.53]]
